name: Build and deploy Python app to Azure Web App - Activityweek3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies (subfolder)
        run: pip install -r python_web_application/requirements.txt

      # (optional) run tests if you have any
      # - run: pytest
      #   working-directory: python_web_application

      - name: Upload artifact (only the app folder)
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            python_web_application/
            !python_web_application/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Activityweek3'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4406DAD34DA64871947C21FA30630551 }}
          package: .   # deploy the downloaded artifact contents
